In [91]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [92]:
df = pd.read_csv("online_retail.csv")

In [93]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [94]:
df.shape

(5300, 8)

In [95]:
df.isnull().sum()

InvoiceNo         0
StockCode         0
Description      12
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID     1205
Country           0
dtype: int64

In [96]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
5295    False
5296    False
5297    False
5298    False
5299    False
Length: 5300, dtype: bool

In [97]:
df.duplicated().sum()

np.int64(85)

In [98]:
df.duplicated().value_counts()

False    5215
True       85
Name: count, dtype: int64

In [99]:
df = df.drop_duplicates()

In [100]:
df.shape

(5215, 8)

In [101]:
df.dtypes

InvoiceNo          str
StockCode          str
Description        str
Quantity         int64
InvoiceDate        str
UnitPrice      float64
CustomerID     float64
Country            str
dtype: object

In [102]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='str')

In [103]:
df.info()

<class 'pandas.DataFrame'>
Index: 5215 entries, 0 to 5299
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   InvoiceNo    5215 non-null   str
 1   StockCode    5215 non-null   str
 2   Description  5203 non-null   str
 3   Quantity     5215 non-null   int64
 4   InvoiceDate  5215 non-null   str
 5   UnitPrice    5215 non-null   float64
 6   CustomerID   4010 non-null   float64
 7   Country      5215 non-null   str
dtypes: float64(2), int64(1), str(5)
memory usage: 366.7 KB

In [104]:
df.describe()

          Quantity    UnitPrice    CustomerID
count  5215.000000  5215.000000   4010.000000
mean      9.360499     3.807640  15829.208728
std     142.039596    12.966069   1746.206475
min   -9360.000000     0.000000  12431.000000
25%       1.000000     1.250000  14491.000000
50%       3.000000     2.510000  15827.000000
75%      12.000000     4.210000  17807.250000
max    2880.000000   607.490000  18239.000000

In [105]:
df["Quantity"].describe()

count    5215.000000
mean        9.360499
std       142.039596
min     -9360.000000
25%         1.000000
50%         3.000000
75%        12.000000
max      2880.000000
Name: Quantity, dtype: float64

In [106]:
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])

In [107]:
df.dtypes

InvoiceNo                 str
StockCode                 str
Description               str
Quantity                int64
InvoiceDate    datetime64[us]
UnitPrice             float64
CustomerID            float64
Country                   str
dtype: object

In [108]:
df["CustomerID"].info()

<class 'pandas.Series'>
Index: 5215 entries, 0 to 5299
Series name: CustomerID
Non-Null Count  Dtype
--------------  -----
4010 non-null   float64
dtypes: float64(1)
memory usage: 81.5 KB

In [109]:
df.info()

<class 'pandas.DataFrame'>
Index: 5215 entries, 0 to 5299
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   InvoiceNo    5215 non-null   str
 1   StockCode    5215 non-null   str
 2   Description  5203 non-null   str
 3   Quantity     5215 non-null   int64
 4   InvoiceDate  5215 non-null   datetime64[us]
 5   UnitPrice    5215 non-null   float64
 6   CustomerID   4010 non-null   float64
 7   Country      5215 non-null   str
dtypes: datetime64[us](1), float64(2), int64(1), str(4)
memory usage: 366.7 KB

In [110]:
df.isnull().sum()

InvoiceNo         0
StockCode         0
Description      12
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID     1205
Country           0
dtype: int64

In [111]:
df["Description"].isna().sum()

np.int64(12)

In [112]:
df = df.dropna(subset=["Description"])

In [113]:
df.shape

(5203, 8)

In [114]:
df.info()

<class 'pandas.DataFrame'>
Index: 5203 entries, 0 to 5299
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   InvoiceNo    5203 non-null   str
 1   StockCode    5203 non-null   str
 2   Description  5203 non-null   str
 3   Quantity     5203 non-null   int64
 4   InvoiceDate  5203 non-null   datetime64[us]
 5   UnitPrice    5203 non-null   float64
 6   CustomerID   4010 non-null   float64
 7   Country      5203 non-null   str
dtypes: datetime64[us](1), float64(2), int64(1), str(4)
memory usage: 365.8 KB

In [115]:
df.isnull().sum()

InvoiceNo         0
StockCode         0
Description       0
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID     1193
Country           0
dtype: int64

In [116]:
df[df["CustomerID"].isnull()].tail(20)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
4285,536756,22910,PAPER CHAIN KIT VINTAGE CHRISTMAS,1,2010-12-02 14:23:00,2.95,NaN,United Kingdom
4286,536756,22439,6 ROCKET BALLOONS,2,2010-12-02 14:23:00,0.65,NaN,United Kingdom
4407,536780,22114,HOT WATER BOTTLE TEA AND SYMPATHY,1,2010-12-02 15:09:00,3.95,NaN,United Kingdom
4408,536780,84032B,CHARLIE + LOLA RED HOT WATER BOTTLE,1,2010-12-02 15:09:00,2.95,NaN,United Kingdom
4409,536780,21481,FAWN BLUE HOT WATER BOTTLE,1,2010-12-02 15:09:00,2.95,NaN,United Kingdom
4410,536780,84032A,CHARLIE+LOLA PINK HOT WATER BOTTLE,1,2010-12-02 15:09:00,2.95,NaN,United Kingdom
4763,536801,21484,CHICK GREY HOT WATER BOTTLE,4,2010-12-02 16:12:00,3.45,NaN,United Kingdom
4764,536801,21067,VINTAGE RED TEATIME MUG,24,2010-12-02 16:12:00,1.25,NaN,United Kingdom
4765,536801,21791,VINTAGE HEADS AND TAILS CARD GAME,12,2010-12-02 16:12:00,1.25,NaN,United Kingdom
4766,536801,21098,CHRISTMAS TOILET ROLL,12,2010-12-02 16:12:00,1.25,NaN,United Kingdom
4767,536801,22952,60 CAKE CASES VINTAGE CHRISTMAS,24,2010-12-02 16:12:00,0.55,NaN,United Kingdom
4768,536801,22086,PAPER CHAIN KIT 50'S CHRISTMAS,6,2010-12-02 16:12:00,2.95,NaN,United Kingdom
4769,536801,82599,FANNY'S REST STOPMETAL SIGN,12,2010-12-02 16:12:00,2.10,NaN,United Kingdom
4770,536801,22113,GREY HEART HOT WATER BOTTLE,4,2010-12-02 16:12:00,3.75,NaN,United Kingdom
4771,536801,22750,FELTCRAFT PRINCESS LOLA DOLL,4,2010-12-02 16:12:00,3.75,NaN,United Kingdom
4772,536801,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,4,2010-12-02 16:12:00,3.75,NaN,United Kingdom
4773,536801,22568,FELTCRAFT CUSHION OWL,4,2010-12-02 16:12:00,3.75,NaN,United Kingdom
4774,536801,22111,SCOTTIE DOG HOT WATER BOTTLE,6,2010-12-02 16:12:00,4.95,NaN,United Kingdom
4775,536801,21559,STRAWBERRY LUNCH BOX WITH CUTLERY,6,2010-12-02 16:12:00,2.55,NaN,United Kingdom
4776,536801,22549,PICTURE DOMINOES,12,2010-12-02 16:12:00,1.45,NaN,United Kingdom

In [117]:
df["Quantity"].dtypes

dtype('int64')

In [118]:
df["Country"].unique()

<StringArray>
['United Kingdom',         'France',      'Australia',    'Netherlands',
        'Germany',         'Norway',           'EIRE']
Length: 7, dtype: str

In [122]:
df['Country'] = df['Country'].replace({'EIRE': "Ireland"})

In [123]:
df["Country"].unique()

<StringArray>
['United Kingdom',         'France',      'Australia',    'Netherlands',
        'Germany',         'Norway',        'Ireland']
Length: 7, dtype: str

In [124]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='str')

In [126]:
df["InvoiceNo"].unique()

<StringArray>
[ '536365',  '536366',  '536367',  '536368',  '536369',  '536370',  '536371',
  '536372',  '536373',  '536374',
 ...
  '536847',  '536848',  '536849', 'C536850',  '536851',  '536852', 'C536853',
 'C536854', 'C536855',  '536856']
Length: 308, dtype: str

In [133]:
df = pd.read_csv("online_retail.csv")

In [134]:
df.shape

(5203, 8)

In [135]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5203 entries, 0 to 5202
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   InvoiceNo    5203 non-null   str
 1   StockCode    5203 non-null   str
 2   Description  5203 non-null   str
 3   Quantity     5203 non-null   int64
 4   InvoiceDate  5203 non-null   str
 5   UnitPrice    5203 non-null   float64
 6   CustomerID   4010 non-null   float64
 7   Country      5203 non-null   str
dtypes: float64(2), int64(1), str(5)
memory usage: 325.3 KB

In [136]:
df.dtypes

InvoiceNo          str
StockCode          str
Description        str
Quantity         int64
InvoiceDate        str
UnitPrice      float64
CustomerID     float64
Country            str
dtype: object

In [141]:
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])

In [142]:
df.dtypes

InvoiceNo                 str
StockCode                 str
Description               str
Quantity                int64
InvoiceDate    datetime64[us]
UnitPrice             float64
CustomerID            float64
Country                   str
dtype: object

In [145]:
df["CustomerID"] = df["CustomerID"].astype("Int64")

In [146]:
df.dtypes

InvoiceNo                 str
StockCode                 str
Description               str
Quantity                int64
InvoiceDate    datetime64[us]
UnitPrice             float64
CustomerID              Int64
Country                   str
dtype: object

In [147]:
df.head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 08:26:00,7.65,17850,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 08:26:00,4.25,17850,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,2010-12-01 08:28:00,1.85,17850,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,2010-12-01 08:28:00,1.85,17850,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,2010-12-01 08:34:00,1.69,13047,United Kingdom

In [148]:
df["CustomerID"].nunique()

215

In [149]:
df["CustomerID"].value_counts()

CustomerID
17850    297
15574    105
17968     81
12433     73
18041     73
        ...
13295      1
14576      1
13145      1
14679      1
18225      1
Name: count, Length: 215, dtype: Int64

In [150]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='str')

In [151]:
df.shape

(5203, 8)

In [152]:
df["Country"].unique()

<StringArray>
['United Kingdom',         'France',      'Australia',    'Netherlands',
        'Germany',         'Norway',        'Ireland']
Length: 7, dtype: str

In [153]:
df["StockCode"].nunique()

1607

In [154]:
df.isnull().sum()

InvoiceNo         0
StockCode         0
Description       0
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID     1193
Country           0
dtype: int64

In [155]:
df[df["CustomerID"].isnull()]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
1406,536544,21773,DECORATIVE ROSE BATHROOM BOTTLE,1,2010-12-01 14:32:00,2.51,<NA>,United Kingdom
1407,536544,21774,DECORATIVE CATS BATHROOM BOTTLE,2,2010-12-01 14:32:00,2.51,<NA>,United Kingdom
1408,536544,21786,POLKADOT RAIN HAT,4,2010-12-01 14:32:00,0.85,<NA>,United Kingdom
1409,536544,21787,RAIN PONCHO RETROSPOT,2,2010-12-01 14:32:00,1.66,<NA>,United Kingdom
1410,536544,21790,VINTAGE SNAP CARDS,9,2010-12-01 14:32:00,1.66,<NA>,United Kingdom
...,...,...,...,...,...,...,...,...
4681,536801,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,4,2010-12-02 16:12:00,3.75,<NA>,United Kingdom
4682,536801,22568,FELTCRAFT CUSHION OWL,4,2010-12-02 16:12:00,3.75,<NA>,United Kingdom
4683,536801,22111,SCOTTIE DOG HOT WATER BOTTLE,6,2010-12-02 16:12:00,4.95,<NA>,United Kingdom
4684,536801,21559,STRAWBERRY LUNCH BOX WITH CUTLERY,6,2010-12-02 16:12:00,2.55,<NA>,United Kingdom
4685,536801,22549,PICTURE DOMINOES,12,2010-12-02 16:12:00,1.45,<NA>,United Kingdom

In [156]:
df.duplicated().sum()

np.int64(0)

In [161]:
(df["Quantity"] < 0).value_counts()

Quantity
False    5123
True       80
Name: count, dtype: int64

In [162]:
df[df["Quantity"] < 0]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548,United Kingdom
...,...,...,...,...,...,...,...,...
5162,C536853,84678,CLASSICAL ROSE SMALL VASE,-1,2010-12-03 10:07:00,2.55,14679,United Kingdom
5163,C536854,22158,3 HEARTS HANGING DECORATION RUSTIC,-1,2010-12-03 10:09:00,2.95,15240,United Kingdom
5164,C536854,22944,CHRISTMAS METAL POSTCARD WITH BELLS,-1,2010-12-03 10:09:00,1.25,15240,United Kingdom
5165,C536854,21871,SAVE THE PLANET MUG,-1,2010-12-03 10:09:00,1.25,15240,United Kingdom
5166,C536855,21527,RED RETROSPOT TRADITIONAL TEAPOT,-4,2010-12-03 10:11:00,7.95,18225,United Kingdom

In [164]:
sales_df = df[df["Quantity"] > 0].copy()

In [165]:
sales_df["Revenue"] = sales_df["Quantity"] * sales_df["UnitPrice"]

In [166]:
returns_df = df[df["Quantity"] < 0].copy()

In [167]:
returns_df["ReturnValue"] = (
    returns_df["Quantity"].abs() * returns_df["UnitPrice"]
)

In [168]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='str')

In [169]:
sales_df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country', 'Revenue'],
      dtype='str')

In [170]:
sales_df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
...,...,...,...,...,...,...,...,...,...
5198,536856,21889,WOODEN BOX OF DOMINOES,12,2010-12-03 10:26:00,1.25,13370,United Kingdom,15.00
5199,536856,22800,ANTIQUE TALL SWIRLGLASS TRINKET POT,4,2010-12-03 10:26:00,3.75,13370,United Kingdom,15.00
5200,536856,79000,MOROCCAN TEA GLASS,12,2010-12-03 10:26:00,0.85,13370,United Kingdom,10.20
5201,536856,22834,HAND WARMER BABUSHKA DESIGN,12,2010-12-03 10:26:00,2.10,13370,United Kingdom,25.20
5202,536856,22865,HAND WARMER OWL DESIGN,12,2010-12-03 10:26:00,2.10,13370,United Kingdom,25.20

In [172]:
returns_df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,ReturnValue
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527,United Kingdom,27.50
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311,United Kingdom,4.65
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548,United Kingdom,19.80
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548,United Kingdom,6.96
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548,United Kingdom,6.96
...,...,...,...,...,...,...,...,...,...
5162,C536853,84678,CLASSICAL ROSE SMALL VASE,-1,2010-12-03 10:07:00,2.55,14679,United Kingdom,2.55
5163,C536854,22158,3 HEARTS HANGING DECORATION RUSTIC,-1,2010-12-03 10:09:00,2.95,15240,United Kingdom,2.95
5164,C536854,22944,CHRISTMAS METAL POSTCARD WITH BELLS,-1,2010-12-03 10:09:00,1.25,15240,United Kingdom,1.25
5165,C536854,21871,SAVE THE PLANET MUG,-1,2010-12-03 10:09:00,1.25,15240,United Kingdom,1.25
5166,C536855,21527,RED RETROSPOT TRADITIONAL TEAPOT,-4,2010-12-03 10:11:00,7.95,18225,United Kingdom,31.80

In [173]:
df[df["UnitPrice"] <= 0]

Empty DataFrame
Columns: [InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country]
Index: []